name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greetings
        run: |
            echo "Hello World!"
            echo "Hello Manohar!"
      - name: Print goodbye
        run: echo "Good Bye!"
